//
// AuthResponseDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AuthResponseDto: Codable {

    public var userId: String?
    public var token: String?
    public var refreshToken: String?

    public init(userId: String? = nil, token: String? = nil, refreshToken: String? = nil) {
        self.userId = userId
        self.token = token
        self.refreshToken = refreshToken
    }


}
