//
// CreatePlayerTeamDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreatePlayerTeamDto: Codable {

    public var apiUserId: String?
    public var teamName: String?

    public init(apiUserId: String? = nil, teamName: String? = nil) {
        self.apiUserId = apiUserId
        self.teamName = teamName
    }


}
