//
// CreateTeamChiefDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateTeamChiefDto: Codable {

    public var firstName: String?
    public var lastName: String
    public var teamId: Int
    public var value: Int
    public var image: String?
    public var personDataId: Int?
    public var strategy: Int?
    public var management: Int?
    public var leading: Int?

    public init(firstName: String? = nil, lastName: String, teamId: Int, value: Int, image: String? = nil, personDataId: Int? = nil, strategy: Int? = nil, management: Int? = nil, leading: Int? = nil) {
        self.firstName = firstName
        self.lastName = lastName
        self.teamId = teamId
        self.value = value
        self.image = image
        self.personDataId = personDataId
        self.strategy = strategy
        self.management = management
        self.leading = leading
    }


}
