//
// PersonData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PersonData: Codable {

    public var _id: Int?
    public var dateOfBirth: Date?
    public var placeOfBirth: String?
    public var country: String?
    public var biography: String?

    public init(_id: Int? = nil, dateOfBirth: Date? = nil, placeOfBirth: String? = nil, country: String? = nil, biography: String? = nil) {
        self._id = _id
        self.dateOfBirth = dateOfBirth
        self.placeOfBirth = placeOfBirth
        self.country = country
        self.biography = biography
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case dateOfBirth
        case placeOfBirth
        case country
        case biography
    }

}
