//
// PlayerTeamLeague.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PlayerTeamLeague: Codable {

    public var playerTeamId: Int?
    public var playerTeam: PlayerTeam?
    public var leagueId: Int?
    public var league: League?

    public init(playerTeamId: Int? = nil, playerTeam: PlayerTeam? = nil, leagueId: Int? = nil, league: League? = nil) {
        self.playerTeamId = playerTeamId
        self.playerTeam = playerTeam
        self.leagueId = leagueId
        self.league = league
    }


}
