//
// Race.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Race: Codable {

    public var _id: Int?
    public var name: String?
    public var technicality: Int?
    public var straights: Int?
    public var lowSpeedCorners: Int?
    public var medSpeedCorners: Int?
    public var highSpeedCorners: Int?
    public var easeOfOvertake: Int?
    public var raceDataId: Int?
    public var raceData: RaceData?

    public init(_id: Int? = nil, name: String? = nil, technicality: Int? = nil, straights: Int? = nil, lowSpeedCorners: Int? = nil, medSpeedCorners: Int? = nil, highSpeedCorners: Int? = nil, easeOfOvertake: Int? = nil, raceDataId: Int? = nil, raceData: RaceData? = nil) {
        self._id = _id
        self.name = name
        self.technicality = technicality
        self.straights = straights
        self.lowSpeedCorners = lowSpeedCorners
        self.medSpeedCorners = medSpeedCorners
        self.highSpeedCorners = highSpeedCorners
        self.easeOfOvertake = easeOfOvertake
        self.raceDataId = raceDataId
        self.raceData = raceData
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case technicality
        case straights
        case lowSpeedCorners
        case medSpeedCorners
        case highSpeedCorners
        case easeOfOvertake
        case raceDataId
        case raceData
    }

}
