//
// UpdatePersonDataDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdatePersonDataDto: Codable {

    public var dateOfBirth: Date?
    public var placeOfBirth: String?
    public var country: String?
    public var biography: String?
    public var _id: Int

    public init(dateOfBirth: Date? = nil, placeOfBirth: String? = nil, country: String? = nil, biography: String? = nil, _id: Int) {
        self.dateOfBirth = dateOfBirth
        self.placeOfBirth = placeOfBirth
        self.country = country
        self.biography = biography
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case dateOfBirth
        case placeOfBirth
        case country
        case biography
        case _id = "id"
    }

}
