//
// TeamDataAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class TeamDataAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTeamDataGet(completion: @escaping ((_ data: [TeamData]?,_ error: Error?) -> Void)) {
        apiTeamDataGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/TeamData
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example=[ {
  "worldChampionships" : 6,
  "polePositions" : 6,
  "firstTeamEntry" : 9,
  "profile" : "profile",
  "fullName" : "fullName",
  "powerUnit" : "powerUnit",
  "id" : 8,
  "chassis" : "chassis",
  "highestRaceFinish" : 3,
  "base" : "base"
}, {
  "worldChampionships" : 6,
  "polePositions" : 6,
  "firstTeamEntry" : 9,
  "profile" : "profile",
  "fullName" : "fullName",
  "powerUnit" : "powerUnit",
  "id" : 8,
  "chassis" : "chassis",
  "highestRaceFinish" : 3,
  "base" : "base"
} ]}]

     - returns: RequestBuilder<[TeamData]> 
     */
    open class func apiTeamDataGetWithRequestBuilder() -> RequestBuilder<[TeamData]> {
        let path = "/api/TeamData"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[TeamData]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTeamDataIdDelete(_id: Int, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        apiTeamDataIdDeleteWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /api/TeamData/{id}
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - parameter _id: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func apiTeamDataIdDeleteWithRequestBuilder(_id: Int) -> RequestBuilder<Void> {
        var path = "/api/TeamData/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTeamDataIdGet(_id: Int, completion: @escaping ((_ data: TeamData?,_ error: Error?) -> Void)) {
        apiTeamDataIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/TeamData/{id}
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "worldChampionships" : 6,
  "polePositions" : 6,
  "firstTeamEntry" : 9,
  "profile" : "profile",
  "fullName" : "fullName",
  "powerUnit" : "powerUnit",
  "id" : 8,
  "chassis" : "chassis",
  "highestRaceFinish" : 3,
  "base" : "base"
}}]
     - parameter _id: (path)  

     - returns: RequestBuilder<TeamData> 
     */
    open class func apiTeamDataIdGetWithRequestBuilder(_id: Int) -> RequestBuilder<TeamData> {
        var path = "/api/TeamData/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<TeamData>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTeamDataIdPatch(_id: Int, body: UpdateTeamDataDto? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        apiTeamDataIdPatchWithRequestBuilder(_id: _id, body: body).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PATCH /api/TeamData/{id}
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - parameter _id: (path)  
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func apiTeamDataIdPatchWithRequestBuilder(_id: Int, body: UpdateTeamDataDto? = nil) -> RequestBuilder<Void> {
        var path = "/api/TeamData/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTeamDataPost(body: CreateTeamDataDto? = nil, completion: @escaping ((_ data: TeamData?,_ error: Error?) -> Void)) {
        apiTeamDataPostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /api/TeamData
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "worldChampionships" : 6,
  "polePositions" : 6,
  "firstTeamEntry" : 9,
  "profile" : "profile",
  "fullName" : "fullName",
  "powerUnit" : "powerUnit",
  "id" : 8,
  "chassis" : "chassis",
  "highestRaceFinish" : 3,
  "base" : "base"
}}]
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<TeamData> 
     */
    open class func apiTeamDataPostWithRequestBuilder(body: CreateTeamDataDto? = nil) -> RequestBuilder<TeamData> {
        let path = "/api/TeamData"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<TeamData>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
