//
// TechnicalChiefsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class TechnicalChiefsAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTechnicalChiefsGet(completion: @escaping ((_ data: [TechnicalChief]?,_ error: Error?) -> Void)) {
        apiTechnicalChiefsGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/TechnicalChiefs
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example=[ {
  "lastName" : "lastName",
  "image" : "image",
  "aerodynamics" : 4,
  "durability" : 1,
  "rating" : 1,
  "maximumSpeed" : 7,
  "firstName" : "firstName",
  "personDataId" : 3,
  "teamId" : 2,
  "id" : 7,
  "value" : 9
}, {
  "lastName" : "lastName",
  "image" : "image",
  "aerodynamics" : 4,
  "durability" : 1,
  "rating" : 1,
  "maximumSpeed" : 7,
  "firstName" : "firstName",
  "personDataId" : 3,
  "teamId" : 2,
  "id" : 7,
  "value" : 9
} ]}]

     - returns: RequestBuilder<[TechnicalChief]> 
     */
    open class func apiTechnicalChiefsGetWithRequestBuilder() -> RequestBuilder<[TechnicalChief]> {
        let path = "/api/TechnicalChiefs"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[TechnicalChief]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTechnicalChiefsGetDetailedTechnicalChiefGet(_id: Int? = nil, completion: @escaping ((_ data: TechnicalChief?,_ error: Error?) -> Void)) {
        apiTechnicalChiefsGetDetailedTechnicalChiefGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/TechnicalChiefs/GetDetailedTechnicalChief
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "lastName" : "lastName",
  "image" : "image",
  "aerodynamics" : 4,
  "durability" : 1,
  "rating" : 1,
  "maximumSpeed" : 7,
  "firstName" : "firstName",
  "personDataId" : 3,
  "teamId" : 2,
  "id" : 7,
  "value" : 9
}}]
     - parameter _id: (query)  (optional)

     - returns: RequestBuilder<TechnicalChief> 
     */
    open class func apiTechnicalChiefsGetDetailedTechnicalChiefGetWithRequestBuilder(_id: Int? = nil) -> RequestBuilder<TechnicalChief> {
        let path = "/api/TechnicalChiefs/GetDetailedTechnicalChief"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "id": _id?.encodeToJSON()
        ])


        let requestBuilder: RequestBuilder<TechnicalChief>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTechnicalChiefsGetTechnicalChiefWithTeamGet(_id: Int? = nil, completion: @escaping ((_ data: TechnicalChief?,_ error: Error?) -> Void)) {
        apiTechnicalChiefsGetTechnicalChiefWithTeamGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/TechnicalChiefs/GetTechnicalChiefWithTeam
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "lastName" : "lastName",
  "image" : "image",
  "aerodynamics" : 4,
  "durability" : 1,
  "rating" : 1,
  "maximumSpeed" : 7,
  "firstName" : "firstName",
  "personDataId" : 3,
  "teamId" : 2,
  "id" : 7,
  "value" : 9
}}]
     - parameter _id: (query)  (optional)

     - returns: RequestBuilder<TechnicalChief> 
     */
    open class func apiTechnicalChiefsGetTechnicalChiefWithTeamGetWithRequestBuilder(_id: Int? = nil) -> RequestBuilder<TechnicalChief> {
        let path = "/api/TechnicalChiefs/GetTechnicalChiefWithTeam"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "id": _id?.encodeToJSON()
        ])


        let requestBuilder: RequestBuilder<TechnicalChief>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTechnicalChiefsGetTechnicalChiefsWithTeamGet(completion: @escaping ((_ data: [Driver]?,_ error: Error?) -> Void)) {
        apiTechnicalChiefsGetTechnicalChiefsWithTeamGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/TechnicalChiefs/GetTechnicalChiefsWithTeam
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example=[ {
  "lastName" : "lastName",
  "growthPotentialId" : 8,
  "isReserveDriver" : true,
  "rating" : 7,
  "accuracy" : 3,
  "growthPotential" : 7,
  "consistency" : 0,
  "personDataId" : 1,
  "id" : 0,
  "braking" : 6,
  "value" : 6,
  "worldChampionships" : 2,
  "image" : "image",
  "overtaking" : 6,
  "pace" : 6,
  "control" : 3,
  "team" : {
    "image" : "image",
    "technicalChief" : {
      "lastName" : "lastName",
      "image" : "image",
      "aerodynamics" : 4,
      "durability" : 1,
      "rating" : 1,
      "maximumSpeed" : 7,
      "firstName" : "firstName",
      "personDataId" : 3,
      "teamId" : 2,
      "id" : 7,
      "value" : 9
    },
    "teamData" : {
      "worldChampionships" : 6,
      "polePositions" : 6,
      "firstTeamEntry" : 9,
      "profile" : "profile",
      "fullName" : "fullName",
      "powerUnit" : "powerUnit",
      "id" : 8,
      "chassis" : "chassis",
      "highestRaceFinish" : 3,
      "base" : "base"
    },
    "teamDataId" : 6,
    "name" : "name",
    "id" : 2,
    "drivers" : [ null, null ],
    "teamChief" : {
      "lastName" : "lastName",
      "image" : "image",
      "leading" : 9,
      "rating" : 9,
      "firstName" : "firstName",
      "personDataId" : 7,
      "management" : 5,
      "teamId" : 1,
      "id" : 1,
      "strategy" : 4,
      "value" : 6
    },
    "teamColor" : "teamColor"
  },
  "adaptability" : 7,
  "aggression" : 3,
  "defendeing" : 0,
  "firstName" : "firstName",
  "personData" : {
    "country" : "country",
    "placeOfBirth" : "placeOfBirth",
    "dateOfBirth" : "2000-01-23T04:56:07.000+00:00",
    "id" : 5,
    "biography" : "biography"
  },
  "raceNumber" : 1,
  "smoothness" : 7,
  "cornering" : 6,
  "teamId" : 5,
  "racecraft" : 4,
  "reactions" : 5,
  "aggressionId" : 3
}, {
  "lastName" : "lastName",
  "growthPotentialId" : 8,
  "isReserveDriver" : true,
  "rating" : 7,
  "accuracy" : 3,
  "growthPotential" : 7,
  "consistency" : 0,
  "personDataId" : 1,
  "id" : 0,
  "braking" : 6,
  "value" : 6,
  "worldChampionships" : 2,
  "image" : "image",
  "overtaking" : 6,
  "pace" : 6,
  "control" : 3,
  "team" : {
    "image" : "image",
    "technicalChief" : {
      "lastName" : "lastName",
      "image" : "image",
      "aerodynamics" : 4,
      "durability" : 1,
      "rating" : 1,
      "maximumSpeed" : 7,
      "firstName" : "firstName",
      "personDataId" : 3,
      "teamId" : 2,
      "id" : 7,
      "value" : 9
    },
    "teamData" : {
      "worldChampionships" : 6,
      "polePositions" : 6,
      "firstTeamEntry" : 9,
      "profile" : "profile",
      "fullName" : "fullName",
      "powerUnit" : "powerUnit",
      "id" : 8,
      "chassis" : "chassis",
      "highestRaceFinish" : 3,
      "base" : "base"
    },
    "teamDataId" : 6,
    "name" : "name",
    "id" : 2,
    "drivers" : [ null, null ],
    "teamChief" : {
      "lastName" : "lastName",
      "image" : "image",
      "leading" : 9,
      "rating" : 9,
      "firstName" : "firstName",
      "personDataId" : 7,
      "management" : 5,
      "teamId" : 1,
      "id" : 1,
      "strategy" : 4,
      "value" : 6
    },
    "teamColor" : "teamColor"
  },
  "adaptability" : 7,
  "aggression" : 3,
  "defendeing" : 0,
  "firstName" : "firstName",
  "personData" : {
    "country" : "country",
    "placeOfBirth" : "placeOfBirth",
    "dateOfBirth" : "2000-01-23T04:56:07.000+00:00",
    "id" : 5,
    "biography" : "biography"
  },
  "raceNumber" : 1,
  "smoothness" : 7,
  "cornering" : 6,
  "teamId" : 5,
  "racecraft" : 4,
  "reactions" : 5,
  "aggressionId" : 3
} ]}]

     - returns: RequestBuilder<[Driver]> 
     */
    open class func apiTechnicalChiefsGetTechnicalChiefsWithTeamGetWithRequestBuilder() -> RequestBuilder<[Driver]> {
        let path = "/api/TechnicalChiefs/GetTechnicalChiefsWithTeam"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[Driver]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTechnicalChiefsIdDelete(_id: Int, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        apiTechnicalChiefsIdDeleteWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /api/TechnicalChiefs/{id}
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - parameter _id: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func apiTechnicalChiefsIdDeleteWithRequestBuilder(_id: Int) -> RequestBuilder<Void> {
        var path = "/api/TechnicalChiefs/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTechnicalChiefsIdGet(_id: Int, completion: @escaping ((_ data: TechnicalChief?,_ error: Error?) -> Void)) {
        apiTechnicalChiefsIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/TechnicalChiefs/{id}
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "lastName" : "lastName",
  "image" : "image",
  "aerodynamics" : 4,
  "durability" : 1,
  "rating" : 1,
  "maximumSpeed" : 7,
  "firstName" : "firstName",
  "personDataId" : 3,
  "teamId" : 2,
  "id" : 7,
  "value" : 9
}}]
     - parameter _id: (path)  

     - returns: RequestBuilder<TechnicalChief> 
     */
    open class func apiTechnicalChiefsIdGetWithRequestBuilder(_id: Int) -> RequestBuilder<TechnicalChief> {
        var path = "/api/TechnicalChiefs/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<TechnicalChief>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTechnicalChiefsIdPatch(_id: Int, body: UpdateTechnicalChiefDto? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        apiTechnicalChiefsIdPatchWithRequestBuilder(_id: _id, body: body).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PATCH /api/TechnicalChiefs/{id}
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - parameter _id: (path)  
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func apiTechnicalChiefsIdPatchWithRequestBuilder(_id: Int, body: UpdateTechnicalChiefDto? = nil) -> RequestBuilder<Void> {
        var path = "/api/TechnicalChiefs/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTechnicalChiefsPost(body: CreateTechnicalChiefDto? = nil, completion: @escaping ((_ data: TechnicalChief?,_ error: Error?) -> Void)) {
        apiTechnicalChiefsPostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /api/TechnicalChiefs
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "lastName" : "lastName",
  "image" : "image",
  "aerodynamics" : 4,
  "durability" : 1,
  "rating" : 1,
  "maximumSpeed" : 7,
  "firstName" : "firstName",
  "personDataId" : 3,
  "teamId" : 2,
  "id" : 7,
  "value" : 9
}}]
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<TechnicalChief> 
     */
    open class func apiTechnicalChiefsPostWithRequestBuilder(body: CreateTechnicalChiefDto? = nil) -> RequestBuilder<TechnicalChief> {
        let path = "/api/TechnicalChiefs"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<TechnicalChief>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
