//
// CreateTechnicalChiefDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateTechnicalChiefDto: Codable {

    public var firstName: String?
    public var lastName: String
    public var teamId: Int
    public var value: Int
    public var image: String?
    public var personDataId: Int?
    public var aerodynamics: Int?
    public var maximumSpeed: Int?
    public var durability: Int?

    public init(firstName: String? = nil, lastName: String, teamId: Int, value: Int, image: String? = nil, personDataId: Int? = nil, aerodynamics: Int? = nil, maximumSpeed: Int? = nil, durability: Int? = nil) {
        self.firstName = firstName
        self.lastName = lastName
        self.teamId = teamId
        self.value = value
        self.image = image
        self.personDataId = personDataId
        self.aerodynamics = aerodynamics
        self.maximumSpeed = maximumSpeed
        self.durability = durability
    }


}
