//
// CreateRaceDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateRaceDto: Codable {

    public var name: String?
    public var technicality: Int?
    public var straights: Int?
    public var lowSpeedCorners: Int?
    public var medSpeedCorners: Int?
    public var highSpeedCorners: Int?
    public var easeOfOvertake: Int?
    public var raceDataId: Int?

    public init(name: String? = nil, technicality: Int? = nil, straights: Int? = nil, lowSpeedCorners: Int? = nil, medSpeedCorners: Int? = nil, highSpeedCorners: Int? = nil, easeOfOvertake: Int? = nil, raceDataId: Int? = nil) {
        self.name = name
        self.technicality = technicality
        self.straights = straights
        self.lowSpeedCorners = lowSpeedCorners
        self.medSpeedCorners = medSpeedCorners
        self.highSpeedCorners = highSpeedCorners
        self.easeOfOvertake = easeOfOvertake
        self.raceDataId = raceDataId
    }


}
