//
// CreateDriverDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateDriverDto: Codable {

    public var firstName: String?
    public var lastName: String
    public var teamId: Int
    public var value: Int
    public var image: String?
    public var personDataId: Int?
    public var raceNumber: Int?
    public var worldChampionships: Int?
    public var cornering: Int
    public var braking: Int
    public var reactions: Int
    public var accuracy: Int
    public var control: Int
    public var smoothness: Int
    public var adaptability: Int
    public var overtaking: Int
    public var defendeing: Int
    public var growthPotentialId: Int
    public var aggressionId: Int
    public var isReserveDriver: Int

    public init(firstName: String? = nil, lastName: String, teamId: Int, value: Int, image: String? = nil, personDataId: Int? = nil, raceNumber: Int? = nil, worldChampionships: Int? = nil, cornering: Int, braking: Int, reactions: Int, accuracy: Int, control: Int, smoothness: Int, adaptability: Int, overtaking: Int, defendeing: Int, growthPotentialId: Int, aggressionId: Int, isReserveDriver: Int) {
        self.firstName = firstName
        self.lastName = lastName
        self.teamId = teamId
        self.value = value
        self.image = image
        self.personDataId = personDataId
        self.raceNumber = raceNumber
        self.worldChampionships = worldChampionships
        self.cornering = cornering
        self.braking = braking
        self.reactions = reactions
        self.accuracy = accuracy
        self.control = control
        self.smoothness = smoothness
        self.adaptability = adaptability
        self.overtaking = overtaking
        self.defendeing = defendeing
        self.growthPotentialId = growthPotentialId
        self.aggressionId = aggressionId
        self.isReserveDriver = isReserveDriver
    }


}
