//
// PlayerTeam.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PlayerTeam: Codable {

    public var _id: Int?
    public var apiUserId: String?
    public var teamName: String?
    public var budget: Int?
    public var collectedPoints: Int?
    public var driverOneId: Int?
    public var driverOne: Driver?
    public var driverTwoId: Int?
    public var driverTwo: Driver?
    public var teamChiefId: Int?
    public var teamChief: TeamChief?
    public var technicalChiefId: Int?
    public var technicalChief: TechnicalChief?
    public var playerTeamLeagues: [PlayerTeamLeague]?
    public var leagues: [League]?

    public init(_id: Int? = nil, apiUserId: String? = nil, teamName: String? = nil, budget: Int? = nil, collectedPoints: Int? = nil, driverOneId: Int? = nil, driverOne: Driver? = nil, driverTwoId: Int? = nil, driverTwo: Driver? = nil, teamChiefId: Int? = nil, teamChief: TeamChief? = nil, technicalChiefId: Int? = nil, technicalChief: TechnicalChief? = nil, playerTeamLeagues: [PlayerTeamLeague]? = nil, leagues: [League]? = nil) {
        self._id = _id
        self.apiUserId = apiUserId
        self.teamName = teamName
        self.budget = budget
        self.collectedPoints = collectedPoints
        self.driverOneId = driverOneId
        self.driverOne = driverOne
        self.driverTwoId = driverTwoId
        self.driverTwo = driverTwo
        self.teamChiefId = teamChiefId
        self.teamChief = teamChief
        self.technicalChiefId = technicalChiefId
        self.technicalChief = technicalChief
        self.playerTeamLeagues = playerTeamLeagues
        self.leagues = leagues
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case apiUserId
        case teamName
        case budget
        case collectedPoints
        case driverOneId
        case driverOne
        case driverTwoId
        case driverTwo
        case teamChiefId
        case teamChief
        case technicalChiefId
        case technicalChief
        case playerTeamLeagues
        case leagues
    }

}
