//
// PlayerTeamLeagueDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PlayerTeamLeagueDto: Codable {

    public var playerTeamId: Int?
    public var leagueId: Int?

    public init(playerTeamId: Int? = nil, leagueId: Int? = nil) {
        self.playerTeamId = playerTeamId
        self.leagueId = leagueId
    }


}
