//
// TeamChief.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TeamChief: Codable {

    public var _id: Int?
    public var lastName: String?
    public var firstName: String?
    public var value: Int?
    public var image: String?
    public var personDataId: Int?
    public var personData: PersonData?
    public var teamId: Int?
    public var strategy: Int?
    public var management: Int?
    public var leading: Int?
    public var rating: Int?

    public init(_id: Int? = nil, lastName: String? = nil, firstName: String? = nil, value: Int? = nil, image: String? = nil, personDataId: Int? = nil, personData: PersonData? = nil, teamId: Int? = nil, strategy: Int? = nil, management: Int? = nil, leading: Int? = nil, rating: Int? = nil) {
        self._id = _id
        self.lastName = lastName
        self.firstName = firstName
        self.value = value
        self.image = image
        self.personDataId = personDataId
        self.personData = personData
        self.teamId = teamId
        self.strategy = strategy
        self.management = management
        self.leading = leading
        self.rating = rating
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case lastName
        case firstName
        case value
        case image
        case personDataId
        case personData
        case teamId
        case strategy
        case management
        case leading
        case rating
    }

}
