//
// TeamData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TeamData: Codable {

    public var _id: Int?
    public var fullName: String?
    public var base: String?
    public var firstTeamEntry: Int?
    public var polePositions: Int?
    public var highestRaceFinish: Int?
    public var worldChampionships: Int?
    public var powerUnit: String?
    public var chassis: String?
    public var profile: String?

    public init(_id: Int? = nil, fullName: String? = nil, base: String? = nil, firstTeamEntry: Int? = nil, polePositions: Int? = nil, highestRaceFinish: Int? = nil, worldChampionships: Int? = nil, powerUnit: String? = nil, chassis: String? = nil, profile: String? = nil) {
        self._id = _id
        self.fullName = fullName
        self.base = base
        self.firstTeamEntry = firstTeamEntry
        self.polePositions = polePositions
        self.highestRaceFinish = highestRaceFinish
        self.worldChampionships = worldChampionships
        self.powerUnit = powerUnit
        self.chassis = chassis
        self.profile = profile
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case fullName
        case base
        case firstTeamEntry
        case polePositions
        case highestRaceFinish
        case worldChampionships
        case powerUnit
        case chassis
        case profile
    }

}
