//
// UpdateTeamDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateTeamDto: Codable {

    public var teamDataId: Int?
    public var image: String?
    public var _id: Int?
    public var name: String?
    public var teamColor: String?

    public init(teamDataId: Int? = nil, image: String? = nil, _id: Int? = nil, name: String? = nil, teamColor: String? = nil) {
        self.teamDataId = teamDataId
        self.image = image
        self._id = _id
        self.name = name
        self.teamColor = teamColor
    }

    public enum CodingKeys: String, CodingKey { 
        case teamDataId
        case image
        case _id = "id"
        case name
        case teamColor
    }

}
